using System.Collections;
using System.Collections.Generic;

namespace ClrDebug
{
    /// <summary>
    /// Provides methods to sequentially iterate through a collection of frozen objects that are generated by the Ngen.exe (Native Image Generator).
    /// </summary>
    /// <remarks>
    /// The ICorProfilerObjectEnum interface is an enumerator. It allows the receiver of an array to pull elements from
    /// the sender at a rate that is appropriate for the receiver. In other words, the receiver is able to explicitly control
    /// the flow of array elements, thereby avoiding the problems related to passing large arrays as method parameters.
    /// Use <see cref="CorProfilerInfo.EnumModuleFrozenObjects"/> to obtain a pointer to the ICorProfilerObjectEnum interface.
    /// </remarks>
    public class CorProfilerObjectEnum : IEnumerable<ObjectID>, IEnumerator<ObjectID>
    {
        public ICorProfilerObjectEnum Raw { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="CorProfilerObjectEnum"/> class.
        /// </summary>
        /// <param name="raw">The raw COM interface that should be contained in this object.</param>
        public CorProfilerObjectEnum(ICorProfilerObjectEnum raw)
        {
            Raw = raw;
        }

        #region Count

        /// <summary>
        /// Gets the total number of frozen objects in the collection.
        /// </summary>
        public int Count
        {
            get
            {
                int pcelt;
                TryGetCount(out pcelt).ThrowOnNotOK();

                return pcelt;
            }
        }

        /// <summary>
        /// Gets the total number of frozen objects in the collection.
        /// </summary>
        /// <param name="pcelt">[out] A pointer to the number of frozen objects in the collection. This method will always return zero in the .NET Framework version 3.5 Service Pack 1 (SP1) and later versions.</param>
        public HRESULT TryGetCount(out int pcelt)
        {
            /*HRESULT GetCount(
            [Out] out int pcelt);*/
            return Raw.GetCount(out pcelt);
        }

        #endregion

        public void Reset()
        {
            if (Raw == null)
                return;

            Raw.Reset();
            Current = default(ObjectID);
        }

        public CorProfilerObjectEnum Clone()
        {
            if (Raw == null)
                return this;

            ICorProfilerObjectEnum clone;
            Raw.Clone(out clone);

            return new CorProfilerObjectEnum(clone);
        }

        #region IEnumerable

        public IEnumerator<ObjectID> GetEnumerator() => this;

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        #endregion
        #region IEnumerator

        public ObjectID Current { get; private set; }

        object IEnumerator.Current => Current;

        public bool MoveNext()
        {
            if (Raw == null)
                return false;

            int fetched;
            ObjectID result;
            var hr = Raw.Next(1, out result, out fetched);

            if (fetched == 1)
                Current = result;
            else
                Current = default(ObjectID);

            return fetched == 1;
        }

        public void Dispose()
        {
        }

        #endregion
    }
}
