using System;

namespace ClrDebug.DbgEng
{
    /// <summary>
    /// Output control flags.
    /// </summary>
    [Flags]
    public enum DEBUG_OUTCTL : uint
    {
        /// <summary>
        /// Output generated by methods called by thisclient will be sent only to this clients
        /// output callbacks.
        /// </summary>
        THIS_CLIENT = 0,

        /// <summary>
        /// Output will be sent to all clients.
        /// </summary>
        ALL_CLIENTS = 1,

        /// <summary>
        /// Output will be sent to all clients except the client generating the output.
        /// </summary>
        ALL_OTHER_CLIENTS = 2,

        /// <summary>
        /// Output will be discarded immediately and will not be logged or sent to callbacks.
        /// </summary>
        IGNORE = 3,

        /// <summary>
        /// Output will be logged but not sent to callbacks.
        /// </summary>
        LOG_ONLY = 4,

        /// <summary>
        /// All send control bits.
        /// </summary>
        SEND_MASK = 7,

        /// <summary>
        /// Do not place output from this client in the global log file.
        /// </summary>
        NOT_LOGGED = 8,

        /// <summary>
        /// Send output to clients regardless of whether the mask allows it or not.
        /// </summary>
        OVERRIDE_MASK = 0x10,

        /// <summary>
        /// Text is markup instead of plain text.
        /// </summary>
        DML = 0x20,

        //Special values which mean leave the output settings unchanged.

        AMBIENT_DML = 0xfffffffe,
        AMBIENT_TEXT = 0xffffffff,
    }
}
