using System.Diagnostics;

namespace ClrDebug.DbgEng
{
    /// <summary>
    /// Encapsulates the results of the <see cref="DebugControl.GetLastEventInformation"/> method.
    /// </summary>
    [DebuggerDisplay("Type = {Type.ToString(),nq}, ProcessId = {ProcessId}, ThreadId = {ThreadId}, ExtraInformationUsed = {ExtraInformationUsed}, Description = {Description}")]
    public struct GetLastEventInformationResult
    {
        /// <summary>
        /// Receives the type of the last event generated by the target. For a list of possible types, see DEBUG_EVENT_XXX.
        /// </summary>
        public DEBUG_EVENT_TYPE Type { get; }

        /// <summary>
        /// Receives the process ID of the process in which the event occurred. If this information is not available, DEBUG_ANY_ID will be returned instead.
        /// </summary>
        public int ProcessId { get; }

        /// <summary>
        /// Receives the thread index (not the thread ID) of the thread in which the last event occurred. If this information is not available, DEBUG_ANY_ID will be returned instead.
        /// </summary>
        public int ThreadId { get; }

        /// <summary>
        /// Receives the size, in bytes, of extra information. If ExtraInformationUsed is NULL, this information is not returned.
        /// </summary>
        public int ExtraInformationUsed { get; }

        /// <summary>
        /// Receives the description of the event. If Description is NULL, this information is not returned.
        /// </summary>
        public string Description { get; }

        public GetLastEventInformationResult(DEBUG_EVENT_TYPE type, int processId, int threadId, int extraInformationUsed, string description)
        {
            Type = type;
            ProcessId = processId;
            ThreadId = threadId;
            ExtraInformationUsed = extraInformationUsed;
            Description = description;
        }
    }
}
