using System;
using System.Runtime.InteropServices;

namespace ClrDebug.DbgEng.Vtbl
{
    [StructLayout(LayoutKind.Sequential)]
    internal struct IDebugClient8Vtbl
    {
        public readonly IntPtr AttachKernel;
        public readonly IntPtr GetKernelConnectionOptions;
        public readonly IntPtr SetKernelConnectionOptions;
        public readonly IntPtr StartProcessServer;
        public readonly IntPtr ConnectProcessServer;
        public readonly IntPtr DisconnectProcessServer;
        public readonly IntPtr GetRunningProcessSystemIds;
        public readonly IntPtr GetRunningProcessSystemIdByExecutableName;
        public readonly IntPtr GetRunningProcessDescription;
        public readonly IntPtr AttachProcess;
        public readonly IntPtr CreateProcess;
        public readonly IntPtr CreateProcessAndAttach;
        public readonly IntPtr GetProcessOptions;
        public readonly IntPtr AddProcessOptions;
        public readonly IntPtr RemoveProcessOptions;
        public readonly IntPtr SetProcessOptions;
        public readonly IntPtr OpenDumpFile;
        public readonly IntPtr WriteDumpFile;
        public readonly IntPtr ConnectSession;
        public readonly IntPtr StartServer;
        public readonly IntPtr OutputServers;
        public readonly IntPtr TerminateProcesses;
        public readonly IntPtr DetachProcesses;
        public readonly IntPtr EndSession;
        public readonly IntPtr GetExitCode;
        public readonly IntPtr DispatchCallbacks;
        public readonly IntPtr ExitDispatch;
        public readonly IntPtr CreateClient;
        public readonly IntPtr GetInputCallbacks;
        public readonly IntPtr SetInputCallbacks;
        public readonly IntPtr GetOutputCallbacks;
        public readonly IntPtr SetOutputCallbacks;
        public readonly IntPtr GetOutputMask;
        public readonly IntPtr SetOutputMask;
        public readonly IntPtr GetOtherOutputMask;
        public readonly IntPtr SetOtherOutputMask;
        public readonly IntPtr GetOutputWidth;
        public readonly IntPtr SetOutputWidth;
        public readonly IntPtr GetOutputLinePrefix;
        public readonly IntPtr SetOutputLinePrefix;
        public readonly IntPtr GetIdentity;
        public readonly IntPtr OutputIdentity;
        public readonly IntPtr GetEventCallbacks;
        public readonly IntPtr SetEventCallbacks;
        public readonly IntPtr FlushCallbacks;
        public readonly IntPtr WriteDumpFile2;
        public readonly IntPtr AddDumpInformationFile;
        public readonly IntPtr EndProcessServer;
        public readonly IntPtr WaitForProcessServerEnd;
        public readonly IntPtr IsKernelDebuggerEnabled;
        public readonly IntPtr TerminateCurrentProcess;
        public readonly IntPtr DetachCurrentProcess;
        public readonly IntPtr AbandonCurrentProcess;
        public readonly IntPtr GetRunningProcessSystemIdByExecutableNameWide;
        public readonly IntPtr GetRunningProcessDescriptionWide;
        public readonly IntPtr CreateProcessWide;
        public readonly IntPtr CreateProcessAndAttachWide;
        public readonly IntPtr OpenDumpFileWide;
        public readonly IntPtr WriteDumpFileWide;
        public readonly IntPtr AddDumpInformationFileWide;
        public readonly IntPtr GetNumberDumpFiles;
        public readonly IntPtr GetDumpFile;
        public readonly IntPtr GetDumpFileWide;
        public readonly IntPtr AttachKernelWide;
        public readonly IntPtr GetKernelConnectionOptionsWide;
        public readonly IntPtr SetKernelConnectionOptionsWide;
        public readonly IntPtr StartProcessServerWide;
        public readonly IntPtr ConnectProcessServerWide;
        public readonly IntPtr StartServerWide;
        public readonly IntPtr OutputServersWide;
        public readonly IntPtr GetOutputCallbacksWide;
        public readonly IntPtr SetOutputCallbacksWide;
        public readonly IntPtr GetOutputLinePrefixWide;
        public readonly IntPtr SetOutputLinePrefixWide;
        public readonly IntPtr GetIdentityWide;
        public readonly IntPtr OutputIdentityWide;
        public readonly IntPtr GetEventCallbacksWide;
        public readonly IntPtr SetEventCallbacksWide;
        public readonly IntPtr CreateProcess2;
        public readonly IntPtr CreateProcess2Wide;
        public readonly IntPtr CreateProcessAndAttach2;
        public readonly IntPtr CreateProcessAndAttach2Wide;
        public readonly IntPtr PushOutputLinePrefix;
        public readonly IntPtr PushOutputLinePrefixWide;
        public readonly IntPtr PopOutputLinePrefix;
        public readonly IntPtr GetNumberInputCallbacks;
        public readonly IntPtr GetNumberOutputCallbacks;
        public readonly IntPtr GetNumberEventCallbacks;
        public readonly IntPtr GetQuitLockString;
        public readonly IntPtr SetQuitLockString;
        public readonly IntPtr GetQuitLockStringWide;
        public readonly IntPtr SetQuitLockStringWide;
        public readonly IntPtr SetEventContextCallbacks;
        public readonly IntPtr SetClientContext;
        public readonly IntPtr OpenDumpFileWide2;
    }
}
