namespace ManagedCorDebug
{
    public enum CorDebugPlatform
    {
        CORDB_PLATFORM_WINDOWS_X86,
        CORDB_PLATFORM_WINDOWS_AMD64,
        CORDB_PLATFORM_WINDOWS_IA64,
        CORDB_PLATFORM_MAC_PPC,
        CORDB_PLATFORM_MAC_X86,
        CORDB_PLATFORM_WINDOWS_ARM,
        CORDB_PLATFORM_MAC_AMD64,
        CORDB_PLATFORM_WINDOWS_ARM64,
    }
}