using System.Runtime.InteropServices;

namespace ClrDebug.PDB
{
    /// <summary>
    /// per module information<para/>
    /// There is one of these subsection entries for each module
    /// in the executable.  The entry is generated by link/ilink.
    /// This table will probably require padding because of the
    /// variable length module name.
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct OMFModule
    {
        /// <summary>
        /// overlay number
        /// </summary>
        public ushort ovlNumber;

        /// <summary>
        /// library that the module was linked from
        /// </summary>
        public ushort iLib;

        /// <summary>
        /// count of number of segments in module
        /// </summary>
        public ushort cSeg;

        /// <summary>
        /// debugging style "CV"
        /// </summary>
        public fixed byte Style[2];

        /// <summary>
        /// describes segments in module<para/>
        /// This value is an array of <see cref="OMFSegDesc"/>
        /// </summary>
        public fixed byte SegInfo[1]; //OMFSegDesc

        /// <summary>
        /// length prefixed module name padded to int word boundary
        /// </summary>
        public fixed byte Name[1];
    }
}
