using System.Runtime.InteropServices;

namespace ClrDebug.PDB
{
    /// <summary>
    /// Source file description<para/>
    /// This table is generated by the linker
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct OMFSourceFile
    {
        /// <summary>
        /// number of segments from source file
        /// </summary>
        public ushort cSeg;

        /// <summary>
        /// reserved
        /// </summary>
        public ushort reserved;

        /// <summary>
        /// base of OMFSourceLine tables<para/>
        /// this array is followed by array of segment start/end pairs followed by
        /// an array of linker indices for each segment in the file
        /// </summary>
        public fixed uint baseSrcLn[1];

        /// <summary>
        /// length of source file name
        /// </summary>
        public ushort cFName;

        /// <summary>
        /// name of file padded to int boundary
        /// </summary>
        public byte Name;
    }
}
