using System.Runtime.InteropServices;

namespace ClrDebug.PDB
{
    /// <summary>
    /// Source line to address mapping table.<para/>
    /// This table is generated by the link/ilink utility from line number
    /// information contained in the object file OMF data.  This table contains
    /// only the code contribution for one segment from one source file.
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct OMFSourceLine
    {
        /// <summary>
        /// linker segment index
        /// </summary>
        public ushort Seg;

        /// <summary>
        /// count of line/offset pairs
        /// </summary>
        public ushort cLnOff;

        /// <summary>
        /// array of offsets in segment
        /// </summary>
        public fixed uint offset[1];

        /// <summary>
        /// array of line lumber in source
        /// </summary>
        public fixed ushort lineNbr[1];
    }
}
