/********************************************************************************
 * This code was generated by a tool.                                           *
 * Please do not modify this file directly - modify DelegateProvider.tt instead *
 ********************************************************************************/
using System;
using System.Runtime.InteropServices;
using static ClrDebug.Extensions;

namespace ClrDebug
{
    internal partial struct DelegateHolder
    {
        private IntPtr proc;

        internal DelegateHolder(IntPtr proc)
        {
            this.proc = proc;
        }
    }

    internal struct DelegateProvider
    {
        private IntPtr hModule;

        internal DelegateProvider(IntPtr hModule)
        {
            this.hModule = hModule;
        }

        public CLRCreateInstanceDelegate CLRCreateInstance
        {
            get
            {
                var export = GetExport(hModule, nameof(CLRCreateInstance));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CLRCreateInstance;
#else
                return Marshal.GetDelegateForFunctionPointer<CLRCreateInstanceDelegate>(export);
#endif
            }
        }

        public CloseCLREnumerationDelegate CloseCLREnumeration
        {
            get
            {
                var export = GetExport(hModule, nameof(CloseCLREnumeration));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CloseCLREnumeration;
#else
                return Marshal.GetDelegateForFunctionPointer<CloseCLREnumerationDelegate>(export);
#endif
            }
        }

        public CloseResumeHandleDelegate CloseResumeHandle
        {
            get
            {
                var export = GetExport(hModule, nameof(CloseResumeHandle));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CloseResumeHandle;
#else
                return Marshal.GetDelegateForFunctionPointer<CloseResumeHandleDelegate>(export);
#endif
            }
        }

        public CreateVersionStringFromModuleDelegate CreateVersionStringFromModule
        {
            get
            {
                var export = GetExport(hModule, nameof(CreateVersionStringFromModule));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CreateVersionStringFromModule;
#else
                return Marshal.GetDelegateForFunctionPointer<CreateVersionStringFromModuleDelegate>(export);
#endif
            }
        }

        public CreateDebuggingInterfaceFromVersionDelegate CreateDebuggingInterfaceFromVersion
        {
            get
            {
                var export = GetExport(hModule, nameof(CreateDebuggingInterfaceFromVersion));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CreateDebuggingInterfaceFromVersion;
#else
                return Marshal.GetDelegateForFunctionPointer<CreateDebuggingInterfaceFromVersionDelegate>(export);
#endif
            }
        }

        public CreateDebuggingInterfaceFromVersionExDelegate CreateDebuggingInterfaceFromVersionEx
        {
            get
            {
                var export = GetExport(hModule, nameof(CreateDebuggingInterfaceFromVersionEx));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CreateDebuggingInterfaceFromVersionEx;
#else
                return Marshal.GetDelegateForFunctionPointer<CreateDebuggingInterfaceFromVersionExDelegate>(export);
#endif
            }
        }

        public CreateDebuggingInterfaceFromVersion2Delegate CreateDebuggingInterfaceFromVersion2
        {
            get
            {
                var export = GetExport(hModule, nameof(CreateDebuggingInterfaceFromVersion2));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CreateDebuggingInterfaceFromVersion2;
#else
                return Marshal.GetDelegateForFunctionPointer<CreateDebuggingInterfaceFromVersion2Delegate>(export);
#endif
            }
        }

        public CreateDebuggingInterfaceFromVersion3Delegate CreateDebuggingInterfaceFromVersion3
        {
            get
            {
                var export = GetExport(hModule, nameof(CreateDebuggingInterfaceFromVersion3));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CreateDebuggingInterfaceFromVersion3;
#else
                return Marshal.GetDelegateForFunctionPointer<CreateDebuggingInterfaceFromVersion3Delegate>(export);
#endif
            }
        }

        public CreateProcessForLaunchDelegate CreateProcessForLaunch
        {
            get
            {
                var export = GetExport(hModule, nameof(CreateProcessForLaunch));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CreateProcessForLaunch;
#else
                return Marshal.GetDelegateForFunctionPointer<CreateProcessForLaunchDelegate>(export);
#endif
            }
        }

        public EnumerateCLRsDelegate EnumerateCLRs
        {
            get
            {
                var export = GetExport(hModule, nameof(EnumerateCLRs));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).EnumerateCLRs;
#else
                return Marshal.GetDelegateForFunctionPointer<EnumerateCLRsDelegate>(export);
#endif
            }
        }

        public GetStartupNotificationEventDelegate GetStartupNotificationEvent
        {
            get
            {
                var export = GetExport(hModule, nameof(GetStartupNotificationEvent));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).GetStartupNotificationEvent;
#else
                return Marshal.GetDelegateForFunctionPointer<GetStartupNotificationEventDelegate>(export);
#endif
            }
        }

        public PSTARTUP_CALLBACK PSTARTUP_CALLBACK
        {
            get
            {
                var export = GetExport(hModule, nameof(PSTARTUP_CALLBACK));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).PSTARTUP_CALLBACK;
#else
                return Marshal.GetDelegateForFunctionPointer<PSTARTUP_CALLBACK>(export);
#endif
            }
        }

        public RegisterForRuntimeStartupDelegate RegisterForRuntimeStartup
        {
            get
            {
                var export = GetExport(hModule, nameof(RegisterForRuntimeStartup));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).RegisterForRuntimeStartup;
#else
                return Marshal.GetDelegateForFunctionPointer<RegisterForRuntimeStartupDelegate>(export);
#endif
            }
        }

        public RegisterForRuntimeStartupExDelegate RegisterForRuntimeStartupEx
        {
            get
            {
                var export = GetExport(hModule, nameof(RegisterForRuntimeStartupEx));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).RegisterForRuntimeStartupEx;
#else
                return Marshal.GetDelegateForFunctionPointer<RegisterForRuntimeStartupExDelegate>(export);
#endif
            }
        }

        public RegisterForRuntimeStartup3Delegate RegisterForRuntimeStartup3
        {
            get
            {
                var export = GetExport(hModule, nameof(RegisterForRuntimeStartup3));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).RegisterForRuntimeStartup3;
#else
                return Marshal.GetDelegateForFunctionPointer<RegisterForRuntimeStartup3Delegate>(export);
#endif
            }
        }

        public ResumeProcessDelegate ResumeProcess
        {
            get
            {
                var export = GetExport(hModule, nameof(ResumeProcess));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).ResumeProcess;
#else
                return Marshal.GetDelegateForFunctionPointer<ResumeProcessDelegate>(export);
#endif
            }
        }

        public UnregisterForRuntimeStartupDelegate UnregisterForRuntimeStartup
        {
            get
            {
                var export = GetExport(hModule, nameof(UnregisterForRuntimeStartup));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).UnregisterForRuntimeStartup;
#else
                return Marshal.GetDelegateForFunctionPointer<UnregisterForRuntimeStartupDelegate>(export);
#endif
            }
        }

        public CLRDataCreateInstanceDelegate CLRDataCreateInstance
        {
            get
            {
                var export = GetExport(hModule, nameof(CLRDataCreateInstance));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).CLRDataCreateInstance;
#else
                return Marshal.GetDelegateForFunctionPointer<CLRDataCreateInstanceDelegate>(export);
#endif
            }
        }

        public MetaDataGetDispenserDelegate MetaDataGetDispenser
        {
            get
            {
                var export = GetExport(hModule, nameof(MetaDataGetDispenser));

#if GENERATED_MARSHALLING
                return new DelegateHolder(export).MetaDataGetDispenser;
#else
                return Marshal.GetDelegateForFunctionPointer<MetaDataGetDispenserDelegate>(export);
#endif
            }
        }
    }
}
